version: '3'
services:
  appointments:
    image:  abdullah4444/appointments:14bea8ab7608ef05224b999d5b4bb47b526eff48
    build: ./path_to_appointments_folder
    ports:
      - "7070:7070"
    networks:
      - app-networkversion: '3'
services:
  appointments:
    build: ./path_to_appointments_folder
    ports:
      - "7070:7070"
    networks:
      - app-network

  doctors:
    image: abdullah4444/doctors:14597d5b4863949b2bd9fb92b15dd3f014dce40d
    build: ./path_to_doctors_folder
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    image:  abdullah4444/frontend_doctors:bff3f32cd28cd4f5c3c76baf16c2b6a96ab93217
    build: ./path_to_frontend_folder
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: doctors:9090
      APPOINTMENTS_SERVICE_URL: appointments:7070
    networks:
      - app-network

networks:
  app-network:


  doctors:
    build: ./path_to_doctors_folder
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    image:  abdullah4444/frontend_doctors:bff3f32cd28cd4f5c3c76baf16c2b6a96ab93217
    build: ./path_to_frontend_folder
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: doctors:9090
      APPOINTMENTS_SERVICE_URL: appointments:7070
    networks:
      - app-network

networks:
  app-network:
