version: '3'
services:
  appointments:
    image:  abdullah4444/appointments:14bea8ab7608ef05224b999d5b4bb47b526eff48
    build: ./path_to_appointments_folder
    ports:
      - "7070:7070"
    networks:
      - app-networkversion: '3'
services:
  appointments:
    build: ./path_to_appointments_folder
    ports:
      - "7070:7070"
    networks:
      - app-network

  doctors:
    image: abdullah4444/doctors:a1023c9c6c31dc4273eb65f31c574d4be965b541
    build: ./path_to_doctors_folder
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    image:  abdullah4444/frontend_doctors:220dec6927a8b28209b3f35d1b2f4f75c3864f62
    build: ./path_to_frontend_folder
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: doctors:9090
      APPOINTMENTS_SERVICE_URL: appointments:7070
    networks:
      - app-network

networks:
  app-network:


  doctors:
    build: ./path_to_doctors_folder
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    image:  abdullah4444/frontend_doctors:220dec6927a8b28209b3f35d1b2f4f75c3864f62
    build: ./path_to_frontend_folder
    ports:
      - "3000:3000"
    environment:
      DOCTORS_SERVICE_URL: doctors:9090
      APPOINTMENTS_SERVICE_URL: appointments:7070
    networks:
      - app-network

networks:
  app-network:
