name: pipeline appointments

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'appointments/**'
  push:
    branches: [ main ]
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./appointments

    steps:
    - name: rep checkout
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: docker buildX
      uses: docker/setup-buildx-action@v3

    - name: dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    

    - name: docker build&push
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:appointments"
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/appointments:${{ github.sha }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.TOKEN }}

    - name: docker compose update
      if: github.event_name == 'push'
      run: |
        cd ../
        sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/appointments:.*|${{ secrets.DOCKERHUB_USERNAME }}/appointments:${{ github.sha }}|" docker-compose.yml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        branch_name=${GITHUB_REF##*/}
        echo ${branch_name}
        git fetch && git checkout ${branch_name}
        git pull
        git add docker-compose.yml
        git commit -m "new tag:appointments"
        git push
