name: PIPELINE FRONTEND

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: REP CHECKOUT
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKENPATH }}

    - name: DOCKER BUILDX
      uses: docker/setup-buildx-action@v3

    - name: DOCKERHUB LOGIN
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    

    - name: DOCKER BUILD AND PUSH
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:frontend"
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend_doctors:${{ github.sha }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.TOKENPATH }}

    - name: DOCKER COMPOSE
      if: github.event_name == 'push'
      run: |
        cd ../
        sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/frontend:.*|${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}|" docker-compose.yml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        branch_name=${GITHUB_REF##*/}
        echo ${branch_name}
        git fetch && git checkout ${branch_name}
        git pull
        git add docker-compose.yml
        git commit -m "new tag :frontend_doctors"
        git push
